### ISSUE TITLE
When a default rgba value is set, it can't be reset

### ISSUE THREAD

**Issue by carolinan** [WPTT/control-color-alpha#3]
If I set a default rgba, for example `'default'  => 'rgba(0,0,0,0.5)',`
and then change the color and try to reset it, the option does not reset correctly 
because there is a # in the field:

![color-alpha](https://user-images.githubusercontent.com/7422055/69910409-721e3700-140b-11ea-88d2-9ba92ff73d45.png)

**Comment by aristath** [comment]
fixed in v1.1 which was a complete rebuild based on react.

**Comment by joyously** [comment]
Now it can't be used standalone.
I am not a fan.

**Comment by aristath** [comment]
What do you mean "standalone"?

**Comment by joyously** [comment]
Without the bulk of React.

**Comment by aristath** [comment]
React is already loaded by wp-core. The control doesn't load a separate instance if React, and it does not include React.
It's just a colorpicker.

**Comment by joyously** [comment]
It is only loaded by core on newer versions of WP.  Using React limits the control's usefulness to WP 5.0+. 
I would have used this on themes that can run on WP 4.7 or even ClassicPress.

**Comment by aristath** [comment]
I have no response to that... WordPress is changing and best coding practices need to follow along. Adopting React is one of the things that sooner or later will have to happen.
We can't guarantee that packages will run on a fork of WordPress, packages are built for WordPress itself. I haven't looked at ClassicPress but I don't see why they would remove react from it - regardless of whether it uses Gutenberg or not.
Packages support the 2 last major releases of WordPress, which means we're past the point of supporting versions older than 5.0.
I understand that some people don't like change, but we're trying to embrace it here, and we're looking to the future. That can't happen by supporting 3-year old versions of WordPress on sites that refuse to update.
A quick search found some alternative controls you could use that haven't been updated in a couple of years, so I'm sure they'll be compatible with older versions of WP:

https://github.com/Codeinwp/customizer-controls/tree/master/customizer-alpha-color-picker

https://braadmartin.com/alpha-color-picker-control-for-the-wordpress-customizer/

https://maddisondesigns.com/2017/05/the-wordpress-customizer-a-developers-guide-part-2/#wpcolorpickeralphacolorpicker
