### ISSUE TITLE
rgba values cannot be edited using the input field

### ISSUE THREAD

**Issue by carolinan** [WPTT/control-color-alpha#4]
If I select a color with an opacity, I cannot edit the rgba values using the input field.
I can _delete_ numbers inside the field, but I cannot add numbers.

(hex values can be edited)

**Comment by aristath** [comment]
fixed in v1.1 which was a complete rebuild based on react.

**Comment by joyously** [comment]
bummer, now I can't use it

**Comment by aristath** [comment]
Why is that?

**Comment by joyously** [comment]
My target is sites without React, like ClassicPress or WP 4.7+.
